package org.usfirst.frc.team4786.robot;

import edu.wpi.first.wpilibj.Joystick;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
	
	//instantiate buttons, sensors and joysticks here
	public Joystick left0;
    public Joystick right1;
    
    public OI() {
    	//construct buttons and joysticks here here
    	//runs commands when buttons pressed
    	
        right1 = new Joystick(1);
        left0 = new Joystick(0);

        /*Button A = new JoystickButton(gameMech, 1);
        The Everything is Awesome code
         1 is button A on xbox
         */
        

	    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
	public static void init(){
		
	}
    public Joystick getLeft() {
        return left0;
    }

    public Joystick getRight() {
        return right1;
    }
    
}